{
 "title": "Triton Inference Server",
 "description": "Nvidia Triton inference server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes{job=\"triton-server\"} / 1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"frida_encoder\"}[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU used",
   "type": "timeseries",
   "description": "GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{gpu_uuid=\"GPU-8fa5c565-1a73-e84d-d8d0-e77353e3df30\"} / 1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  },
  {
   "title": "Gpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"triton-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}